services:
  # -----------------------------------------------------------------------------------------
  # User Service

  user-service:
    restart: always
    build:
      context: ${USER_SERVICE_PATH}/src/
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:8080"
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_NAME: bookem_userdb_db
      DB_USER: bookem_userdb_user
      DB_PASSWORD: password123
      JWT_PRIVATE_KEY_PATH: /app/keys/private_key.key
      JWT_PUBLIC_KEY_PATH: /app/keys/public_key.pem
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
      SERVICE_NAME: user-service
      DEPLOYMENT_ENV: dev
    depends_on:
      user-db:
        condition: service_healthy
    volumes:
      - ${USER_SERVICE_PATH}/keys/private_key.key:/app/keys/private_key.key:ro
      - ${USER_SERVICE_PATH}/keys/public_key.pem:/app/keys/public_key.pem:ro
      - ./logs/user-service:/app/logs
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider --tries=1 --no-verbose http://user-service:8080/healthz || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: bookem_userdb_db
      POSTGRES_USER: bookem_userdb_user
      POSTGRES_PASSWORD: password123
    volumes:
      - type: volume
        source: user_pgdata
        target: /var/lib/postgresql/data
    ports:
      - "${USER_SERVICE_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5

  # -----------------------------------------------------------------------------------------
  # Room Service

  room-service:
    restart: always
    build:
      context: ${ROOM_SERVICE_PATH}/src/
      dockerfile: Dockerfile
    ports:
      - "${ROOM_SERVICE_PORT}:8080"
    environment:
      DB_HOST: room-db
      DB_PORT: 5432
      DB_NAME: bookem_roomdb_db
      DB_USER: bookem_roomdb_user
      DB_PASSWORD: password123
      JWT_PUBLIC_KEY_PATH: /app/keys/public_key.pem
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
      SERVICE_NAME: room-service
      DEPLOYMENT_ENV: dev
    depends_on:
      user-db:
        condition: service_healthy
    volumes:
      - ${ROOM_SERVICE_PATH}/keys/public_key.pem:/app/keys/public_key.pem:ro
      - ${ROOM_SERVICE_PATH}/nginx/images:/app/images/
      - ./logs/room-service:/app/logs
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider --tries=1 --no-verbose http://room-service:8080/healthz || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  room-db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: bookem_roomdb_db
      POSTGRES_USER: bookem_roomdb_user
      POSTGRES_PASSWORD: password123
    volumes:
      - type: volume
        source: room_pgdata
        target: /var/lib/postgresql/data
    ports:
      - "${ROOM_SERVICE_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5

  room-image-server:
    restart: always
    build:
      context: ${ROOM_SERVICE_PATH}/nginx
      dockerfile: Dockerfile
    ports:
      - "${ROOM_SERVICE_IMAGES_PORT}:80"    
    volumes:
      - ${ROOM_SERVICE_PATH}/nginx/images:/usr/share/nginx/html/images/

  # -----------------------------------------------------------------------------------------
  # Reservation service

  
  reservation-service:
    restart: always
    build:
      context: ${RESERVATION_SERVICE_PATH}/src/
      dockerfile: Dockerfile
    ports:
      - "${RESERVATION_SERVICE_PORT}:8080"
    environment:
      DB_HOST: reservation-db
      DB_PORT: 5432
      DB_NAME: bookem_reservationdb_db
      DB_USER: bookem_reservationdb_user
      DB_PASSWORD: password123
      JWT_PRIVATE_KEY_PATH: /app/keys/private_key.key
      JWT_PUBLIC_KEY_PATH: /app/keys/public_key.pem
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
      SERVICE_NAME: reservation-service
      DEPLOYMENT_ENV: dev
    depends_on:
      reservation-db:
        condition: service_healthy
    volumes:
      - ${RESERVATION_SERVICE_PATH}/keys/public_key.pem:/app/keys/public_key.pem:ro
      - ./logs/reservation-service:/app/logs
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider --tries=1 --no-verbose http://reservation-service:8080/healthz || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  reservation-db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: bookem_reservationdb_db
      POSTGRES_USER: bookem_reservationdb_user
      POSTGRES_PASSWORD: password123
    volumes:
      - type: volume
        source: reservation_pgdata
        target: /var/lib/postgresql/data
    ports:
      - "${RESERVATION_SERVICE_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5


  # -----------------------------------------------------------------------------------------
  # Web app

  web-app:
    restart: always
    profiles: [full]
    build:
      context: ${WEB_APP_PATH}/
      dockerfile: Dockerfile
    volumes:
      - ./temp/web-app-env.js:/usr/share/nginx/html/env.js
    ports:
      - "80:80"

  # -----------------------------------------------------------------------------------------
  # Utility, debug and telemetry

  adminer:
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4318:4318"     # OTLP HTTP
      - "16686:16686"   # Jaeger UI

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: always

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./logs:/app/logs
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:12345"

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  node_exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    pid: "host"
    command:
      - '--no-collector.arp'
      - '--no-collector.bonding'
      - '--no-collector.conntrack'
      - '--no-collector.diskstats'
      - '--no-collector.filefd'
      - '--no-collector.hwmon'
      - '--no-collector.infiniband'
      - '--no-collector.ipvs'
      - '--no-collector.nfs'
      - '--no-collector.sockstat'
      - '--no-collector.textfile'
      - '--no-collector.vmstat'
      - '--collector.filesystem.ignored-mount-points=^/(run/user|var/lib/docker/.+)'
      - '--collector.filesystem.ignored-fs-types=tmpfs,overlay'
 
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  user_pgdata:
    name: bookem-user-service-db-volume
  room_pgdata:
    name: bookem-room-service-db-volume  
  reservation_pgdata:
    name: bookem-reservation-service-db-volume
  grafana-storage:
    name: bookem-grafana-storage-volume
  prom_data: